statement -> exprStmt
    | forStmt
    | ifStmt
    | printStmt
    | returnStmt
    | whileStmt
    | block ;

block -> "{" declaration* "}" ;

declaration ->classDecl
    | funDecl
    | varDecl
    | statement ;